name: Java CI with Ant (Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest  # This runs on the latest Windows runner provided by GitHub

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Apache Ant
      run: |
        choco install ant  # Installs Apache Ant using Chocolatey package manager

    - name: Run Ant build
      run: ant -noinput -buildfile nbproject/build-impl.xml
